# Generated by Django 5.2.16 on 2026-07-31 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('unit', models.CharField(choices=[('meter', 'Meter'), ('pcs', 'Pcs'), ('roll', 'Roll'), ('box', 'Box'), ('set', 'Set')], default='pcs', max_length=10)),
                ('min_stock_alert', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('match_material_group', models.CharField(blank=True, help_text='e.g. Dropwire, Router, IPTV', max_length=50)),
                ('match_length_or_band', models.CharField(blank=True, help_text='e.g. 100 Meter / Dual Band / Wifi 6', max_length=50)),
                ('match_connector', models.CharField(blank=True, help_text='e.g. APC/APC, APC/UPC', max_length=20)),
                ('match_condition', models.CharField(blank=True, choices=[('NEW', 'New'), ('REFURBISHED', 'Refurbished')], help_text='Leave blank if not applicable', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='consumption_uploads/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PROCESSING', max_length=12)),
                ('total_rows', models.IntegerField(default=0)),
                ('matched_rows', models.IntegerField(default=0)),
                ('unmatched_rows', models.IntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='inventory.region')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='inventory.vendor')),
            ],
            options={
                'ordering': ['region__name', 'vendor__name', 'name'],
                'unique_together': {('vendor', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consumed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='inventory.material')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['warehouse', 'material', 'date'], name='inventory_s_warehou_dc4041_idx')],
                'unique_together': {('date', 'warehouse', 'material')},
            },
        ),
        migrations.CreateModel(
            name='PODStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_stations', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('warehouse', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ConsumptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('pod_station_name', models.CharField(blank=True, max_length=150)),
                ('raw_material_text', models.CharField(blank=True, help_text='Materials/Category/Type as read from the file', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('matched', models.BooleanField(default=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='inventory.consumptionupload')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_records', to='inventory.material')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.region')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_records', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['warehouse', 'material', 'date'], name='inventory_c_warehou_535ac7_idx'), models.Index(fields=['date'], name='inventory_c_date_a00284_idx')],
            },
        ),
    ]
