# Generated by Django 5.2.16 on 2026-07-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionrecord',
            name='raw_type_text',
            field=models.CharField(blank=True, help_text='The Type column exactly as read from the file', max_length=100),
        ),
    ]
